# Generated by Django 5.0.1 on 2024-02-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_images_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
