# Generated by Django 5.0.1 on 2024-02-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_brand_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_id',
        ),
    ]
