# Generated by Django 5.0.1 on 2024-02-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_brand_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
