# Generated by Django 4.1.10 on 2024-02-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_contact_alter_product_description_and_more'),
        ('store_app', '0014_contact_us_alter_product_description_and_more'),
    ]

    operations = [
    ]
